# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Dagbani spellchecker"
dag = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Dagbani, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
dag = "TRANSLATE: A spellchecker for Dagbani, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.dag"

[windows]
system_product_code = "{31902232-972B-4A87-A5C2-A53FF8052C45}_is1"

[package.speller]
name = "Dagbani"
version = "0.1.0"

[package.grammar]
name = "Dagbani"
version = "0.1.0"

[package.tts-text-proc]
name = "Dagbani"
version = "0.1.0"

[package.hyphenator]
name = "Dagbani"
version = "0.1.0"
