template = "https://github.com/giellalt/template-lang-und"
rev_id = 272
template_sha = "f40ff07ea2383e4e83e8ad0ff88b795ceaf841e6"

[replacements]
__GLOTTOLOG_ID__ = "dagb1246"
__LICENSE__ = "LGPLv3"
__REPO__ = "lang-dag"
__UND2C__ = "dag"
__UNDEFINED__ = "Dagbani"
__UND__ = "dag"
