template = "https://github.com/giellalt/template-lang-und"
rev_id = 268
template_sha = "444a55f5c0c0489e8f1dcde2639b74c44c24dffb"

[replacements]
__GLOTTOLOG_ID__ = "dagb1246"
__LICENSE__ = "LGPLv3"
__REPO__ = "lang-dag"
__UND2C__ = "dag"
__UNDEFINED__ = "Dagbani"
__UND__ = "dag"
